### PR TITLE
Update to add additional gendered words to analyze (womanist, latina, latino)

### PR DESCRIPTION
**Pull request by M0nica**
Would it be okay to add womanist and latina to the `analyze.py`?  I added womanist since I think it incorporates more people but if it makes sense for this project I can also add latina.

> Definition: A black feminist or feminist of color, according to Alice Walker, who first publicly used the term; someone who is committed to the wholeness and well-being of all of humanity, male and female. ... Alice Walker also used "womanist" to refer to a woman who loves other women, whether platonically or sexually.

### CODE REVIEW

**Comment by ajdavis** [comment]
Looks good to me. I'd guess that there are a *few* people with "womanist" in their bios who aren't female, but to guess that they are *all* female is at least as good as the other guesses in this code. Please do add "latina" and "latino", I think that's even more likely to correlate with gender identity.

**Comment by M0nica** [comment]
Okay, great. I agree with that. "womanist" should have less false positive for female than "feminist". I will update with latino/latina

**Comment by ajdavis** [comment]
Thanks!

**Comment by ajdavis** [comment]
This is now deployed on https://www.proporti.onl/

**Pull request merged**
